config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  get 'home', to: 'home#index'

  get 'mentions/users',           to: 'mentions#users'
  get 'latest-updates',           to: 'activities#latest_updates', 
                                  as: :latest_updates
  get 'about',                    to: 'static#about'
  get 'rsvps/paginate',           to: 'rsvps#paginate'
  get 'notifications/paginate',   to: 'notifications#paginate'
  get 'friend_requests/paginate', to: 'friend_requests#paginate'
  get 'messages/paginate',        to: 'conversations#paginate'
  get 'contact',                  to: 'static#contact'
  get 'privacy',                  to: 'static#privacy'
  get 'tos',                      to: 'static#tos'
  get 'search',                   to: 'search#index'
  get 'search/users',             to: 'search#users'
  get 'search/hashtags',          to: 'search#hashtags'
  get 'messages',                 to: 'conversations#index'
  get 'notifications/dropdown',   to: 'notifications#dropdown'
  get 'messages/dropdown',        to: 'conversations#dropdown'
  get 'friend_requests/dropdown', to: 'friend_requests#dropdown'
  get 'profile/edit',             to: 'profiles#edit'
  get 'profile/edit/header',      to: 'profiles#edit_header'
  get 'nearby/events',            to: 'nearby#events'
  get 'nearby/trainers',          to: 'nearby#trainers'
  get 'nearby/posts',             to: 'nearby#posts'
  post 'embedly',                 to: 'posts#embedly', as: 'embedly'
  post 'pusher/auth'
  get 'pusher/notifications',     to: 'pusher#notifications'
  get 'pusher/feed',              to: 'pusher#feed'
  get 'pusher/updates',           to: 'pusher#updates'
  post 'map/search/:id',          to: 'map#search'
  get 'map/sightings/:lat/:lng',  to: 'map#sightings', lat: /-?\d+(\.\d+)/, lng: /-?\d+(\.\d+)/
  get 'map/gyms/:lat/:lng',       to: 'map#gyms', lat: /-?\d+(\.\d+)/, lng: /-?\d+(\.\d+)/
  get 'map/pokestops/:lat/:lng',  to: 'map#pokestops', lat: /-?\d+(\.\d+)/, lng: /-?\d+(\.\d+)/
  
  get 'change-team',              to: 'change_team#new'
  patch 'change-team',             to: 'change_team#create'

  resources :sightings do
    resources :reports
  end
  resources :gyms do
    resources :reports
  end
  resources :pokestops do
    resources :reports
  end
  
  resources :mentions, only: [:index]
  resources :friend_requests, path: "friends/requests"
  delete 'friends/:id', to: "friends#destroy", as: :friends
  resources :notifications
  resources :activities, only: [:index]
  resources :hashtags, only: [:index, :show]

  resources :events do
    resources :rsvps
    get 'hosting', on: :collection
    get 'rsvps', on: :collection
    put "update_image", to: 'events#update_image'
    delete "remove_image", to: 'events#remove_image'
  end

  resources :users, only: [:index, :show, :update] do
    resources :profiles
    resources :locations
    get 'likes', to: 'users#likes'
    get 'favorites', to: 'profiles#favorites'
    get 'about', to: 'profiles#show'
    get 'photos', to: 'photos#index'
    get 'friends', to: 'friends#index'
    delete 'remove_avatar', to: 'profiles#remove_avatar'
    put 'update_avatar', to: 'profiles#update_avatar'
    put 'update_header', to: 'profiles#update_header'
  end  

  resources :photos do
    resources :comments
    resources :likes, only: [:index, :create]
    resources :locations
    delete 'likes', to: 'likes#destroy'
  end

  resources :status_messages, only: [:new, :create, :update]   
  resources :messages, only: [:new, :create, :show]

  resources :conversations, only: [:index] do
    member do
      post :reply
    end
  end

  resources :posts, only: [:show, :destroy] do
    resources :locations
    resources :comments
    resources :favorites, only: [:index, :create]
    resources :likes, only: [:index, :create]
    resources :shares, only: [:index, :new, :create]
    delete 'likes', to: 'likes#destroy'
    delete 'favorites', to: 'favorites#destroy'
    delete 'shares', to: 'shares#destroy'
  end

  devise_for :users, path: '', skip: [:registrations], path_names: {sign_in: 'login', sign_out: 'logout', password: 'password-reset', confirmation: 'confirm-account'}, controllers: {confirmations: 'devise/confirmations'}

  as :user do
    get 'register', to: 'users/registrations#new', as: 'new_user_registration'
    post 'register', to: 'devise/registrations#create', as: 'user_registration'
    get 'users/cancel', to: 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'settings', to: 'users#edit', as: 'edit_user_registration'
    put 'settings', to: 'users#update'
  end    

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets[:sidekiq]['username'] && password == Rails.application.secrets[:sidekiq]['password']
  end  

  mount Sidekiq::Web => '/sidekiq'
  
  authenticated :user do 
    root to: "dashboard#index", as: "authenticated_root"
  end

  root to: "home#index"  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_footer_and_bg

  def index
    @news = NewsFeed.limit(3)
    @events = Event.featured.upcoming.recent.limit(3)
    @hashtags = Hashtag.trending.limit(4)
  end

private
  def set_footer_and_bg
    @home_page = true
    @footer_page = true    
  end  
end

app/views/home/_login_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <center><h4 class="modal-title" id="loginLabel">Log in to Catch 'Em Go</h4></center>
</div>
<div class="modal-body-content">
  <div class="modal-body">
    <center><%= image_tag "nav_logo.png" %></center>
    <%= form_for(:user, url: session_path(:user), html: {class: 'nav-login-form'}) do |f| %>
      <div class="form-group">
        <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group">
        <%=  f.check_box :remember_me %>
        <%= f.label :remember_me %>
        <small> . </small>
        <%= link_to "Forgot Password?", new_user_password_path %> 
      </div>        
      <div class="form-group">
        <%= f.submit "Login", class: 'btn btn-primary form-control' %>
      </div>   
    <% end %>
  </div>
  <div class="modal-footer">
    <center><small>Don't have an account? <%= link_to "Sign up", new_user_registration_path %></small></center>
  </div>
</div>

app/views/home/_signup_call.html.erb
<div class="module sign-up-call">
  <h3>New To Catch 'Em Go?</h3>
  <div>Sign up to connect with other Pokemon GO trainers, or find meetups and events near you!</div>
  <div><%= link_to "Sign Up", new_user_registration_path, class: "btn sign-up-call-btn" %></div>
</div>

app/views/home/_signup_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <center><h4 class="modal-title" id="signupLabel">Sign up for Catch 'Em Go</h4></center>
</div>
<div class="modal-body-content">
  <div class="modal-body">
    <center><%= image_tag "nav_logo.png" %></center>
    <center>
      <h4>Not on Catch 'Em Go? Sign up to connect with other Pokemon GO trainers, or find meetups and events near you.</h4>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary signup-modal-btn" %>
    </center>
  </div>
  <div class="modal-footer">
    <center><small>Have an account? <%= link_to "Log in", new_user_session_path %></small></center>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="margin-top-20 margin-bottom-20"><center><%= image_tag "index/index_logo.png", class: "index-header" %></center></div>
  <div class="row">
    <div class="col-md-12">
      <% @hashtags.each do |hashtag| %>
        <div class="col-md-3 col-padding">
          <%= link_to "##{hashtag.display}", hashtag_path(hashtag.display), {style: "display:block;", class: "module tab"} %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-padding">
    <div class="row">
      <div class="col-md-12">
        <div class="module">
          <%= render 'map/header' %>
          <div id='map'></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h4>Events:</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% @events.each do |event| %>
        <div class="col-md-3 col-padding">
          <div class="news-box clearfix">
            <%= link_to event do %>
              <img src="<%= event.image? ? event.image_url(:sidebar) : asset_path("events/banner_placeholder.png") %>" class="img-responsive" width="280" height="114">
            <% end %>
            <div class="news-headline"><%= link_to truncate(event.name, length: 32), event %></div>
            <div class="news-body">
              <div>
                <b>Hosted By:</b> 
                <img src="<%= event.host.profile.team.present? ? event.host.profile.team.image_url(:flair) : asset_path("no_team.png") %>" width="25">
                <%= link_to event.host.full_name, event.host %> <span class="event-hosted-username"><%= link_to "@#{event.host.username}", event.host %></span>
              </div>
              <div><b>Date:</b> <%= event_dates(event) %></div>
              <div class="margin-bottom-10"><b>Time:</b> <%= event_times(event) %></div>
              <div><%= event.place.name %></div>
              <div><%= event.place.formatted_address %></div>
            </div> 
          </div>
        </div>
      <% end %>
      <div class="col-md-3 col-padding">
        <div class="news-box">
          <%= render 'home/signup_call' %>
        </div>
      </div>
    </div>               
  </div>  
  <div class="row">
    <div class="col-md-12">
      <h4>News:</h4>
    </div>
  </div>
  <div class="row margin-bottom-60">
    <div class="col-md-12">
      <% @news.each do |news| %>
        <div class="col-md-3 col-padding">
          <div class="news-box clearfix">
            <%= link_to news.full_url, target: "_blank" do %>
              <img src="<%= news.image_url(:thumb_medium) %>" class="img-responsive" width="280" height="114">
            <% end %>
            <div class="news-headline"><%= link_to truncate(news.title, length: 32), news.full_url, target: "_blank" %></div>
            <div class="news-body"><%= news.description %></div>
          </div>  
        </div>
      <% end %>
    </div>               
  </div>
</div>